//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestitiBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Prestito = new HashSet<Prestito>();
        }
    
        public int Codice { get; set; }
        public string Autore { get; set; }
        public string Titolo { get; set; }
        public string Editore { get; set; }
        public Nullable<int> Anno { get; set; }
        public string Luogo { get; set; }
        public string Pagine { get; set; }
        public string Classificazione { get; set; }
        public string Collocazione { get; set; }
        public Nullable<int> Copie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestito> Prestito { get; set; }
    }
}
